### ISSUE TITLE
no funcionan los comentarios nuevos en ordenar por curso

### ISSUE THREAD

**Issue by verosupervero** [lugfi/dolly#45]
si vamos a "ver por docente" los comentarios de 1c21 se ven, ahora si vamos a ver por curso, no se ven. AYUDA, no lo puedo sacar que es lo que anda mal :(

**Comment by LuisCusihuaman** [comment]
Hola, buenas @verosupervero !

Yo veo que esta funcionando todo ok, esto te sigue pasando?
![Peek 2021-08-15 20-29](https://user-images.githubusercontent.com/43934057/129495878-6bfc9e1b-3ff7-42dc-bc41-104c505bbd50.gif)
