### ISSUE TITLE
Proyecto inspirado en Dolly

### ISSUE THREAD

**Issue by regexPattern** [lugfi/dolly#80]
Hola que tal? Soy estudiante de informática en FIUBA y la verdad es que me gusta mucho el proyecto de Dolly. Actualmente estoy aprendiendo desarrollo web y me gustaría saber si puedo utilizar la información (calificaciones de maestros, catedras, comentarios, etc...) que este proyecto ha recopilado.

Mi intención es solo para hacer un proyecto de practica y luego subir el repo como para tenerlo de muestra, pero nada mas, para nada intentar crear una alternativa real a Dolly ni mucho menos (en el mejor de los casos capaz agrego cosas extra que después se pueden considerar para Dolly).

Solo quería preguntar si puedo utilizar los datos, ya que veo que están guardados en archivos JSON en este mismo repo. Gracias.

**Comment by fdnk** [comment]
Hola Carlos, sí, por supuesto.

El codigo fuente de dolly está acá: https://github.com/lugfi/dolly

La base de datos de dolly es este hermoso txt:
https://dollyfiuba.com/gente.txt
Los json de las materias nos los cede Fede del Mazo generalmente, del
FIUBA-Plan.

Cualquier cosa que necesites, no dudes en escribirme.

Saludos,
Fernando Danko

**Comment by regexPattern** [comment]
Perfecto muchas gracias. Cuando lo termine todo ajunto un link del repo en este thread para que vean si les sirve algo de lo que implemento para tal vez considerarlo para Dolly.

**Comment by regexPattern** [comment]
Hola que tal @fdnk como vas? He ido avanzando al suave con el proyecto, pero ya va que quiere. Ahora estoy implementando funcionalidad para filtrar las catedras de una materia, y me preguntaba si ustedes tienen alguna manera de saber cuales son las catedras que se estan dictando en el cuatrimestre actual y cuales no, para darles prioridad a las que se estan dictando este cuatri (o estan por dictarse pues cuando se anuncia la oferta para cada cuatri).

La forma en la que lo pienso hacer es a traves del SIU obtener la oferta del cuatrimestre mas reciente, pero esto implicaria que al compilar el sitio alguien provea sus credenciales para poder descargar esta info ya que los del SIU no tienen un endpoint del que pueda sacar estos datos, si o si tengo que hacer scraping ya desde la cuenta. Por eso pregunto que si ustedes tienen alguna forma de hacer esto que quiza sea mas facil? Si no no hay drama, me voy por la via del SIU.

**Comment by verosupervero** [comment]
Hola Carlos, nosotros sacamos la info de los jsons que genera del mazo, justamente cuatrimestre a cuatrimestre la obtenemos del proyecto de él, y el lo obtiene de una página: ofertahoraria.fi.uba.ar.
Creo que esto lo tenemos documentado en el proyecto en la wiki si lo revisas.
Saludos!

**Comment by regexPattern** [comment]
Hola que tal? Después de muchos meses (y reescribir el frontend varias veces), finalmente creo tener una primera version del proyecto. Pueden checkearlo [acá](https://fiuba-reviews.vercel.app/) y me dicen que les parece.

**Comment by LuisCusihuaman** [comment]
@regexPattern tremendo trabajo 👏👏👏👏 realmente me quito el sombrero 🎩

Solo lo pude ver muy por arriba _(as an unboxing xd)_, pero estos son un par de puntitos que vi:
- Muy buena decisión el uso de rust para consumir la información de dolly, parsearla, normalizarla y actualizar los datos de la db. 👍🦀
- Acierto, en el uso de svelte, tanto para el cliente como lo Server Side Rendering. 🌐🖌️
- Acierto en el uso de tailwindcss, para el prototypado rapido de la idea y puesta en marcha. 🎨✨
- Acierto, en el uso de drizzle y postgresql, como ORM popular y como base de datos opensource. Hasta ya es compatible con nuevos patrones de edge runtime/computing, hace que la velocidad del renderizado sea increíblemente rápido y no te mates definiendo una API o endpoints. 🚀🔍🛠️
- Veo que estuviste leyendo como funcionaba dolly, porque esta implementación https://github.com/regexPattern/fiuba-reviews/blob/main/src/routes/materias/%5BcodigoMateria%5D/%2Blayout.server.ts#L30 no es tribial de hacer y requiería entender como se hacia la analitica de  dolly. 📚💻
- Acierto en la dockerización de los procesos de rust y el uso de compose (no sé si es porque usas podman) es buenísimo tenerlo. 🐳🛠️
- Acierto en el uso de pnpm, para una iteración más rápida en el desarrollo con librerías de npm. 🚀📦
- Todos los puntos respecto a DX (Developer Experience) veo que están cubiertos, hasta tenes un prettier configurado, a lo mucho faltará eslint (pero solo como un detalle). 🛠️💻
- Acierto en el uso de vercel como plataforma de despliegue para rápidas iteraciones. 🚀🌐
- El uso de IA para la generación de la descripción es tremendo 👏👏👏
- Toda la aplicación respeta el espíritu de dolly, pero está construida como una aplicación de los tiempos modernos. 🔥🚀

**Comment by LuisCusihuaman** [comment]
@regexPattern Este es mi tg para que sigamos hablando! https://t.me/EduCusihuaman

**Comment by regexPattern** [comment]
Muchas gracias por el comentario. Justamente el objetivo del proyecto era modernizar un poco la aplicación original. Inicialmente pensé que solo iba a construir un nuevo frontend, pero terminó evolucionando a una aplicación mucho más compleja, principalmente por todo lo que está bajo el capó cuando se corre inician los servicios del compose.

No es una alternativa 1:1 con la app original, ya que en el caso de la mía pues toca hostear una base de datos, pero la idea es que tomen las ideas que quieren implementar en la aplicación original para mejorar (desde mi punto de vista) la experiencia de todos los estudiantes que usamos Dolly.

**Comment by regexPattern** [comment]
Dale, muchisimas gracias. Voy a ver si a lo largo del año puedo hacer otra util para mantener sincronizados los datos, porque por el momento solo está el scraper de datos que se corre cuando se popula la base de datos inicial, ya después se desligan los comentarios de mi proyecto con los de Dolly.

**Comment by sotlucas** [comment]
Recién veo que pudiste completar la app! Por mi parte hice varios intentos para mejorar la experiencia de Dolly y nunca me cerraba. Lo que hiciste quedó espectacular, congrats @regexPattern!! 🎉
